runtime: php83  # or php81 if using PHP 8.1
entrypoint: serve index.php  # Use your main PHP file as the entry point
env: standard  # Standard environment

handlers:
  - url: /images
    static_files: images
    upload: images/.*  # Allow uploading of image files
  - url: /.*  # Route all other requests to the Slim application
    script: auto  # Automatically handle requests with your Slim app
